### ISSUE TITLE
NPM Issues

### ISSUE THREAD

**Issue by nexusvue** [TurplePurtle/juniper-bot#1]
Hey, absolutely amazing work, just looking for some pointers on where to start with this one. 

Commands / brief run through.

Any idea linux distro, just tried installing on Ubuntu and it wouldn't recognise node.js 

Amazing work!

**Comment by TurplePurtle** [comment]
Hi, thanks for the praise. I've updated the readme to list the commands.

Make sure node is in your `PATH`. The only thing `npm start` does currently is run `node main.js`, so as long as node works for other things, this should work fine.

You'll also need to install ffmpeg (or libav for Ubuntu) to use the audio-related commands, and Python 2.7 to install some of the audio-related npm packages.

Out of curiosity, how did you find this bot?

**Comment by nexusvue** [comment]
Well, you're the only person so far on the internet to come up under the search query instagram discord, and apparently the only project on here?

Thanks for taking the time to edit / update me on the above, highly appreciated, working on a cool project which could really put to use the hard work you've laid down so far!

Anyways, happy to start going through and checking this bad boy out. 

Thanks again.

**Comment by TurplePurtle** [comment]
No problem. If what you're interested in is the Instagram part, then the file you want is `juniper-cache.js`.

**Comment by nexusvue** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle juniper@0.0.1~prestart: juniper@0.0.1
6 silly lifecycle juniper@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle juniper@0.0.1~start: juniper@0.0.1
8 verbose lifecycle juniper@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle juniper@0.0.1~start: PATH: /usr/share/npm/bin/node-gyp-bin:/root/InstaBot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle juniper@0.0.1~start: CWD: /root/InstaBot
11 silly lifecycle juniper@0.0.1~start: Args: [ '-c', 'node main.js' ]
12 silly lifecycle juniper@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle juniper@0.0.1~start: Failed to exec start script
14 verbose stack Error: juniper@0.0.1 start: `node main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid juniper@0.0.1
16 verbose cwd /root/InstaBot
17 error Linux 4.8.0-30-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error juniper@0.0.1 start: `node main.js`
22 error Exit status 1
23 error Failed at the juniper@0.0.1 start script 'node main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the juniper package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs juniper
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls juniper
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by nexusvue** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle juniper@0.0.1~prestart: juniper@0.0.1
6 silly lifecycle juniper@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle juniper@0.0.1~start: juniper@0.0.1
8 verbose lifecycle juniper@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle juniper@0.0.1~start: PATH: /usr/share/npm/bin/node-gyp-bin:/root/InstaBot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle juniper@0.0.1~start: CWD: /root/InstaBot
11 silly lifecycle juniper@0.0.1~start: Args: [ '-c', 'node main.js' ]
12 silly lifecycle juniper@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle juniper@0.0.1~start: Failed to exec start script
14 verbose stack Error: juniper@0.0.1 start: `node main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid juniper@0.0.1
16 verbose cwd /root/InstaBot
17 error Linux 4.8.0-30-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error juniper@0.0.1 start: `node main.js`
22 error Exit status 1
23 error Failed at the juniper@0.0.1 start script 'node main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the juniper package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs juniper
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls juniper
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
